stages:
  - build
  - mirror

before_script:
  - set -e
  - set -u
  - set -o pipefail

build:
  stage: build
  image: node:carbon
  cache:
    paths:
    - node_modules/
  artifacts:
    name: $CI_PIPELINE_ID
    paths:
    - dist/*
    expire_in: 1 week
  script:
    - yarn
    - yarn build
    - cp manifest.json dist/manifest.json
    - cp icon-128.png dist/icon-128.png

mirror:
  stage: mirror
  image: bravissimolabs/alpine-git:latest
  only:
    - master
  script:
    - git push https://runebaas:$TOKEN@github.com/runebaas/newtab.git origin/master:master -f
